apiVersion: hyperspike.io/v1
kind: Repo
metadata:
  labels:
    app.kubernetes.io/name: gitea-operator
    app.kubernetes.io/managed-by: kustomize
  name: mirror-repo-sample
spec:
  private: true
  org:
    name: test
  mirror: true
  cloneAddr: https://github.com/example/source-repo.git
  mirrorInterval: 1h
  # TODO(user): Add fields here
